export const experienceData = [
  {
    id: 6,
    title: "Freelance FullStack Developer",
    company: "Self-Employed",
    location: "Remote",
    period: "September 2025 — Present",
    type: "Freelance",
    technologies: [
      "React",
      "Next.js",
      "TypeScript",
      "React Native",
      "Expo",
      "Node.js",
      "Express",
      "PostgreSQL",
      "Prisma",
      "MongoDB",
      "TanStack Query",
      "NextAuth",
      "Docker",
      "TailwindCSS",
      "Git",
    ],
    responsibilities: [
      "Worked directly with clients end-to-end — scoping, architecture, full-stack build, and deployment — shipping production web and mobile products as a solo developer.",
      "Built a complete operating system for the hotel business: platform admins, hotel owners, branch staff, and travel agencies each get a purpose-built portal and guests get a mobile app to browse and book — all on one shared backend so availability, pricing, and permissions stay consistent everywhere.",
      "Delivered a multi-tenant system that replaces the spreadsheet sprawl of warehouse and distribution businesses — customers, suppliers, inventory, invoicing, and the truck-and-driver fleet in one place — with strict tenant isolation so one deployment serves many businesses and no one ever sees another tenant's data, plus access-controlled, auditable records.",
      "Created a zero-setup, in-browser playground that makes Git's hardest concepts click: learners type real Git commands and watch a live commit graph draw branches, merges, rebases, and conflicts as they happen, with a puzzle mode that challenges them to reach a target graph shape.",
    ],
    category: "software",
  },
  {
    id: 1,
    title: "Lead FullStack Developer",
    company: "Turina Tech",
    location: "Remote",
    period: "September 2024 — September 2025",
    type: "Full-time",
    technologies: [
      "ReactJs",
      "TailwindCSS",
      "React-Native",
      "Expo",
      "Docker",
      "Git",
      "Spring Boot",
      "Jira",
      "Firebase",
      ".NET",
      "Agile Dev.",
    ],
    responsibilities: [
      "Written the code to fix an existing issue, implemented new features, and added unit test cases.",
      "Participating in daily meetings with team members and checking the daily progress of our implementation.",
      "Creating tasks and user stories, and following up on these tasks' progress and team members' development.",
      "Created a mobile application and implemented iOS and Android features and differences are added.",
      "Collaborated with the QA team in daily meetings and updated code based on their daily test reports.",
      "After the assigned test's implementation is completed, a new pull request and PR are approved and merged into the main branch, so Incorporated with other developers.",
      "Helped improve the Figma design and gave UI/UX design teams more feedback.",
    ],
    category: "software",
  },
  {
    id: 2,
    title: "Computer Technician",
    company: "Dawson College",
    location: "Montreal, QC",
    period: "August 2024 — October 2024",
    type: "Contract",
    responsibilities: [
      "Fixed broken computers, printers or other devices.",
      "Deployed new Windows, MacOS or iOS based on the school security restrictions.",
      "Installed, configured, and upgraded software applications and operating systems.",
      "Troubleshooted and resolved software issues, including operating system errors and application crashes.",
      "Performed regular maintenance on computer systems to ensure operated efficiently.",
      "Troubleshoot hardware and software issues, including operating systems, applications, and network connectivity.",
      "Install, configure, and maintain IT equipment such as workstations, printers, and network devices in clinics and head office locations.",
      "Assist in setting up and managing user accounts, passwords, and permissions in accordance with IT policies.",
    ],
    category: "technical",
  },
  {
    id: 3,
    title: "Intern FullStack Developer",
    company: "Saadat Development",
    location: "Remote",
    period: "April 2024 — June 2024",
    type: "Internship",
    technologies: [
      "ReactJs",
      "TailwindCSS",
      "React-Query",
      "Socket.IO",
      "JWT",
      "React-Router",
      "Docker",
      "Git",
      "Jotai",
    ],
    responsibilities: [
      "Written the code to fix an existing issue or implemented 24 new features.",
      "Created 60 new test cases with Jest and React-Testing Library.",
      "Conducted a thorough review of the code base, creating a report to document and address any errors found, ensuring high code quality.",
      "Executed and managed global state to ensure data consistency across the application with Jotai.",
      "Enforced React-Query to handle integrated front-end components with RESTful APIs and data fetching, caching, and error handling.",
      "Incorporated the version control systems to manage code changes and collaborate with other developers.",
    ],
    category: "software",
  },
  {
    id: 4,
    title: "Computer Technician",
    company: "Dawson College",
    location: "Montreal, QC",
    period: "October 2023 — December 2023",
    type: "Contract",
    responsibilities: [
      "Fixed broken computers, printers or other devices.",
      "Deployed new Windows, MacOS or iOS based on the school security restrictions.",
      "Installed, configured, and upgraded software applications and operating systems.",
      "Troubleshooted and resolved software issues, including operating system errors and application crashes.",
      "Performed regular maintenance on computer systems to ensure operated efficiently.",
    ],
    category: "technical",
  },
  {
    id: 5,
    title: "Computer Technician",
    company: "Lester B. Pearson SB",
    location: "Montreal, QC",
    period: "November 2019 — February 2020",
    type: "Contract",
    responsibilities: [
      "Answered the school administration's and teachers' requests regarding computer or technical questions and suggestions.",
      "Repaired malfunctioning computers, printers, smart-boards, projections or other devices.",
      "Documented troubleshooting steps and solutions for future reference.",
    ],
    category: "technical",
  },
];
