export const projects = [
  {
    id: "0",
    title: "SaveEasy",
    company: "Turina Technologies",
    technologies: [
      "TypeScript",
      "React-Native",
      "Expo",
      "Docker",
      "Git",
      ".NET",
      "MSServer",
    ],
    achievements: [
      "Engineered an AI-powered receipt processing pipeline using [OpenAI/Gemini] and OCR, achieving a 98.5% extraction accuracy rate for key financial fields (Total, Tax, Vendor, Date).",
      "Architected a high-performance reporting engine capable of generating accountant-ready PDF/CSV reports in under 1.5 seconds, even for datasets exceeding 500+ transactions.",
      "Implemented robust data security by securing connection strings through environment variables and applying Row-Level Security (RLS) to ensure users can only access their own financial records.",
      "Apple and Google Play Store.",
    ],
    gradient: "from-emerald-600 to-teal-600",
  },
  {
    id: "1",
    title: "VDrivers",
    company: "Turina Technologies",
    technologies: [
      "Spring Boot",
      "Maven",
      "MSSQL",
      "TypeScript",
      "React-Native",
      "Expo",
      "Docker",
      "Git",
      "TanStackQuery",
      "Axios",
    ],
    achievements: [
      "Architected a 3-tier application ecosystem (Driver App, Business App, and Web Admin) using React Native/Expo and Spring Boot, enabling seamless job matching for 100+ concurrent users during peak rush hours.",
      "Engineered a real-time communication layer using Firebase Cloud Messaging (FCM), achieving a 99.9% notification delivery rate and reducing worker response times by 70% (from minutes to seconds).",
      "Developed a high-performance backend with Spring Boot and Maven, implementing RESTful APIs optimized for mobile clients with TanStack Query to ensure data consistency and offline caching.",
      "Optimized mission-critical SQL Server queries for real-time driver availability, reducing database search latency by 45% through the implementation of Stored Procedures and Non-Clustered Indexes.",
    ],
    gradient: "from-blue-600 to-cyan-600",
  },
  {
    title: "Restaurant Project",
    company: "Saadat Development",
    technologies: [
      "TypeScript",
      "ReactJs",
      "NextJs",
      "TailwindCSS",
      "NextAuthJs",
      "LeafletJS",
      "JWT",
      "Git",
    ],
    id: "2",
    achievements: [
      "Optimized delivery logistics by implementing a 'Shortest Path' algorithm, resulting in a 15% improvement in delivery time estimates and a 10% reduction in total fuel/distance costs.",
      "Developed a responsive, mobile-first UI using Tailwind CSS, ensuring consistent branding and high performance across web and mobile platforms.",
      "Designed a scalable NoSQL schema with MongoDB and Mongoose, managing complex data relations between recipes, user geolocation data, and order history. Implemented secure authentication flows integrating NextAuth.js and JWT.",
    ],
    gradient: "from-purple-600 to-pink-600",
  },
];
