import type { ProjectDetailsItemType } from "~/types/ProjectDetailsItemType";
import type { ProjectType } from "~/types/ProjectType";

export const projects: ProjectType[] = [
  {
    id: "0",
    title: "SaveEasy",
    company: "Turina Technologies",
    technologies: [
      "TypeScript",
      "React-Native",
      "Expo",
      "Docker",
      "Git",
      ".NET",
      "MSServer",
    ],
    achievements: [
      "Engineered an AI-powered receipt processing pipeline using [OpenAI/Gemini] and OCR, achieving a 98.5% extraction accuracy rate for key financial fields (Total, Tax, Vendor, Date).",
      "Architected a high-performance reporting engine capable of generating accountant-ready PDF/CSV reports in under 1.5 seconds, even for datasets exceeding 500+ transactions.",
      "Implemented robust data security by securing connection strings through environment variables and applying Row-Level Security (RLS) to ensure users can only access their own financial records.",
      "Apple and Google Play Store.",
    ],
    mainImage: "/images/SaveEasyMain.png",
    images: [
      "/images/SaveEasyMain.png",
      "/images/SaveEasyExp.png",
      "/images/SaveEasyAuth.png",
    ],
    gradient: "from-emerald-600 to-teal-600",
    link: "https://apps.apple.com/ca/app/saveeasy/id6738876717",
  },
  {
    id: "1",
    title: "VDrivers",
    company: "Turina Technologies",
    technologies: [
      "Spring Boot",
      "Maven",
      "MSSQL",
      "TypeScript",
      "React-Native",
      "Expo",
      "Docker",
      "Git",
      "TanStackQuery",
      "Axios",
    ],
    achievements: [
      "Architected a 3-tier application ecosystem (Driver App, Business App, and Web Admin) using React Native/Expo and Spring Boot, enabling seamless job matching for 100+ concurrent users during peak rush hours.",
      "Engineered a real-time communication layer using Firebase Cloud Messaging (FCM), achieving a 99.9% notification delivery rate and reducing worker response times by 70% (from minutes to seconds).",
      "Developed a high-performance backend with Spring Boot and Maven, implementing RESTful APIs optimized for mobile clients with TanStack Query to ensure data consistency and offline caching.",
      "Optimized mission-critical SQL Server queries for real-time driver availability, reducing database search latency by 45% through the implementation of Stored Procedures and Non-Clustered Indexes.",
    ],
    gradient: "from-blue-600 to-cyan-600",
  },
  {
    id: "3",
    title: "Assignment Organizer",
    company: "Cuneyt Yildirim",
    technologies: [
      "SwiftUI",
      "Swift",
      "CoreData",
      "CloudKit",
      "WidgetKit",
      "UserNotifications",
      "Keychain",
      "CryptoKit",
      "Git",
    ],
    achievements: [
      "Architected a native iOS academic ecosystem using SwiftUI and CoreData, implementing a multi-view organization system that allows students to filter assignments by Date, Priority, Subject, and Completion status.",
      "Engineered a seamless cross-device synchronization layer using NSPersistentCloudKitContainer, ensuring real-time data continuity and conflict resolution across all user devices signed into iCloud.",
      "Developed a high-visibility productivity suite by integrating WidgetKit for 'at-a-glance' home screen tracking and a custom Local Notification system that proactively alerts users to upcoming deadlines.",
      "Secured sensitive student data by implementing a local authentication system using Keychain Services for token storage and CryptoKit for salted password hashing.",
    ],
    gradient: "from-teal-600 to-emerald-600",
    mainImage: "/images/mainScreen.png",
    images: [
      "/images/assignment/IMG_2502.png",
      "/images/assignment/IMG_2503.png",
      "/images/assignment/IMG_2504.png",
      "/images/assignment/IMG_2505.png",
      "/images/assignment/IMG_2506.png",
      "/images/assignment/IMG_2507.png",
      "/images/assignment/IMG_2508.png",
    ],
    link: "https://apps.apple.com/ca/app/assignment-organizer/id6757585892",
  },
  {
    id: "4",
    title: "HabitTracking",
    company: "Cuneyt Yildirim",
    technologies: [
      "SwiftUI",
      "SwiftData",
      "CloudKit",
      "Swift Charts",
      "Combine",
      "WidgetKit",
      "Git",
    ],
    achievements: [
      "Designed a versatile habit-tracking engine supporting six distinct data types (Boolean, Numeric, Duration, Checklist, Streak, Periodic) to accommodate diverse user goals and measurable behavioral changes.",
      "Integrated a sophisticated mood-correlation system featuring 20 distinct emotional states, allowing users to visualize the relationship between mental well-being and habit consistency through interactive charts.",
      "Implemented an advanced visual analytics dashboard using the Swift Charts framework, providing users with heatmaps, trend lines, and completion rate statistics across weekly, monthly, and yearly intervals.",
      "Leveraged SwiftData and CloudKit to build a modern, reactive persistence layer that automates data synchronization while maintaining a zero-latency, offline-first user experience.",
    ],
    gradient: "from-fuchsia-600 to-violet-600",
    mainImage: "/images/HabitMain.png",
    images: [
      "/images/habit/IMG_2515.png",
      "/images/habit/IMG_2516.png",
      "/images/habit/IMG_2517.png",
      "/images/habit/IMG_2518.png",
      "/images/habit/IMG_2519.png",
      "/images/habit/IMG_2520.png",
      "/images/habit/IMG_2521.png",
      "/images/habit/IMG_2521.png",
    ],
    link: "https://apps.apple.com/ca/app/habitizer/id6757522855",
  },
  {
    id: "5",
    title: "Tutoring Manager",
    company: "Respect Development",
    technologies: [
      "React Native",
      "Expo",
      "Firebase",
      "TanStack Query",
      "Cloud Functions",
      "FCM",
      "Node.js",
    ],
    gradient: "from-cyan-600 to-slate-600",
    achievements: [
      "Architected a real-time session management ecosystem for iOS, Android, and Web, utilizing Firebase Firestore listeners and TanStack Query to achieve near-instant UI updates (under 200ms).",
      "Engineered an automated notification engine using Expo Notifications and Firebase Cloud Messaging, delivering critical session reminders 15 minutes prior to start times.",
      "Developed a secure, server-side student onboarding workflow using Firebase Cloud Functions and the Admin SDK, allowing instructors to manage student credentials without local authentication conflicts.",
      "Implemented a dual-workflow request system (Enrollment & Timeslots) with role-based access control, ensuring distinct, secure experiences for both instructors and students.",
    ],
    images: [
      "/images/booking_bee/TuttorMain.png",
      "/images/booking_bee/TutorWeekschedule.png",
      "/images/booking_bee/TutorThemes.png",
      "/images/booking_bee/TutorSess.png",
      "/images/booking_bee/TutorInst.png",
      "/images/booking_bee/Tutordetailsession.png",
      "/images/booking_bee/TutorProfile.png",
    ],
    link: "https://bookingbee-lnw2.onrender.com/profile",
  },
  {
    title: "Restaurant Project",
    company: "Saadat Development",
    technologies: [
      "TypeScript",
      "ReactJs",
      "NextJs",
      "TailwindCSS",
      "NextAuthJs",
      "LeafletJS",
      "JWT",
      "Git",
    ],
    id: "2",
    achievements: [
      "Optimized delivery logistics by implementing a 'Shortest Path' algorithm, resulting in a 15% improvement in delivery time estimates and a 10% reduction in total fuel/distance costs.",
      "Developed a responsive, mobile-first UI using Tailwind CSS, ensuring consistent branding and high performance across web and mobile platforms.",
      "Designed a scalable NoSQL schema with MongoDB and Mongoose, managing complex data relations between recipes, user geolocation data, and order history. Implemented secure authentication flows integrating NextAuth.js and JWT.",
    ],
    gradient: "from-purple-600 to-pink-600",
    mainImage: "/images/restaurant.gif",
  },
  {
    title: "Budget Manager",
    company: "",
    technologies: ["SwiftUI", "Vision", "CoreData", "iCloudDatabase", "Git"],
    id: "7",
    achievements: [
      "Built SwiftUI budget app with responsive design and custom UI components",
      "Implemented Vision framework for receipt scanning and text recognition",
      "Created CoreData model with iCloud sync for multi-device access",
      "Developed financial dashboards using Swift Charts with animations",
      "Added ML-powered spending insights using CreateML",
      "Integrated biometric authentication and Home Screen widgets",
      "Optimized performance for handling thousands of transactions",
    ],
    gradient: "from-purple-600 to-pink-600",
    images: [
      "/images/budget/IMG_2476.png",
      "/images/budget/IMG_2477.png",
      "/images/budget/IMG_2478.png",
      "/images/budget/IMG_2479.png",
      "/images/budget/IMG_2480.png",
      "/images/budget/IMG_2481.png",
      "/images/budget/IMG_2482.png",
      "/images/budget/IMG_2483.png",
      "/images/budget/IMG_2484.png",
      "/images/budget/IMG_2485.png",
      "/images/budget/IMG_2486.png",
      "/images/budget/IMG_2487.png",
      "/images/budget/IMG_2488.png",
    ],
  },
  {
    id: "6",
    title: "ADT Learning App",
    company: "Cuneyt Yildirim",
    technologies: [
      "TypeScript",
      "React 19",
      "Vite",
      "TailwindCSS",
      "React Hooks",
    ],
    link: "https://data-structure-cy.netlify.app/",
    achievements: [
      "Built an interactive educational platform covering 8 sorting algorithms with animated step-by-step bar chart visualizations and per-element role coloring (compare, swap, pivot, sorted).",
      "Implemented 12 Gang of Four design pattern reference pages — each with tabbed Overview, Example, Consequences, and multi-language Code sections covering TypeScript, Python, Java, and C++.",
      "Authored a custom UI component library (@cuneytyildirim/ui) with four visual paradigms (Flat, Skeumorphic, Neumorphic, Glass), shared via npm across projects.",
      "Designed a generic sort-step engine and reusable panel component system to eliminate repeated UI code across all algorithm and pattern pages.",
    ],
    gradient: "from-violet-600 to-indigo-600",
  },
  {
    title: "Camping Project",
    company: "",
    technologies: [
      "JavaScript",
      "ReactJs",
      "LeafletJS",
      "NodeJS",
      "MongoDB",
      "ExpressJS",
      "JWT",
      "Cloudinary",
      "Git",
    ],
    id: "7",
    achievements: [
      "Developed full-stack camping platform using MERN stack (MongoDB, Express, React, Node.js) with RESTful API architecture",
      "Implemented interactive map interface using LeafletJS with campground clustering, custom markers, and geolocation features",
      "Built user authentication system with JWT tokens, encrypted passwords, and role-based access control (user/admin)",
      "Created campground CRUD operations allowing users to create, read, update, and delete camping locations with images",
      "Designed responsive React frontend with reusable components, React Router for navigation, and Context API for state management",
      "Implemented image upload functionality with Cloudinary integration for storing and optimizing campground photos",
      "Developed review system allowing users to rate campgrounds and leave comments with star ratings",
      "Built search and filtering functionality for campgrounds by location, amenities, price range, and ratings",
      "Implemented pagination and infinite scroll for better performance with large campground datasets",
      // "Created admin dashboard for managing users, campgrounds, and reviews with moderation capabilities",
      "Optimized MongoDB queries with indexing and aggregation pipelines for faster campground searches",
      // "Implemented email notifications for booking confirmations, review responses, and password resets",
      // "Deployed full-stack application using AWS EC2/Docker or Heroku with CI/CD pipeline using GitHub Actions",
    ],
    gradient: "from-purple-600 to-pink-600",
    images: ["/images/camp/camping1.gif", "/images/camp/camping2.gif"],
  },
  {
    title: "Hotel Management System",
    company: "Personal Project (5 Years)",
    technologies: [
      "Node.js",
      "Express",
      "Next.js",
      "TypeScript",
      "MongoDB",
      "Mongoose",
      "JWT",
      "NextAuth",
      "React Native",
      "Expo",
      "Redux",
      "Redux Sagas",
      "TailwindCSS",
      "Docker",
      "Nginx",
      "Husky",
      "Jest",
    ],
    id: "8",
    link: "https://hotel-management-systemwebportal-8m9pn7uka.vercel.app/",
    achievements: [
      "Architected a 6-application ecosystem — Express backend, Admin portal, Owner portal, Hotel portal, Agency portal, and a React Native mobile app — all orchestrated via Docker Compose with Nginx reverse proxy.",
      "Built a shared Express/MongoDB REST API (port 4000) serving all 4 Next.js portals with centralized JWT auth, role management, and booking/room logic.",
      "Engineered granular RBAC across the agency→hotel→branch hierarchy, enabling fine-grained permission assignment per user per branch.",
      "Developed a customer-facing React Native/Expo mobile app with Redux + Redux Sagas for async state, supporting auth, hotel discovery, room booking, and favourites.",
      "Implemented Husky pre-commit hooks, Jest test suites across all portals, and Nginx routing for all 4 web portals under a single domain.",
    ],
    gradient: "from-indigo-600 to-blue-600",
    images: [],
  },
  {
    title: "Family Tree",
    company: "Personal Project",
    technologies: [
      "React",
      "TypeScript",
      "D3.js",
      "TanStack Router",
      "TanStack Query",
      "TailwindCSS",
      "Vite",
    ],
    id: "9",
    achievements: [
      "Built an interactive family tree visualization using D3.js SVG rendering with custom multi-generational layout algorithm supporting marriage connections and sibling grouping.",
      "Implemented zoom, pan, and drag controls via D3 zoom behavior allowing users to navigate large family trees seamlessly.",
      "Designed a unified tree builder that resolves parent-child relationships bidirectionally through both explicit children arrays and fatherId/motherId references.",
      "Integrated TanStack Router and TanStack Query for type-safe routing and server-state management across the family member CRUD workflows.",
    ],
    gradient: "from-green-600 to-teal-600",
    images: [],
  },
  {
    title: "GitHub Dev Tracker",
    company: "Personal Project",
    technologies: [
      "React Router",
      "TypeScript",
      "GitHub REST API",
      "GitHub GraphQL API",
      "Recharts",
      "TailwindCSS",
      "Docker",
    ],
    id: "10",
    achievements: [
      "Built a GitHub OAuth SSR dashboard using React Router with server-side session management, fetching live contribution data via both REST and GraphQL APIs.",
      "Implemented a contribution heatmap rendering 52 weeks of daily activity with color-coded intensity levels and month/day axis labels.",
      "Engineered a streak calculation algorithm that correctly handles current-day and yesterday edge cases across the full contribution calendar.",
      "Visualized developer insights with Recharts: contributions breakdown (pie), top repositories by commits (bar), and language distribution (pie).",
    ],
    gradient: "from-slate-600 to-gray-700",
    images: ["/images/git/IMG_2510", "/images/git/IMG_2511"],
  },
  {
    title: "Spaced Repetition iOS",
    company: "Cuneyt Yildirim",
    technologies: [
      "SwiftUI",
      "Swift",
      "CoreData",
      "CloudKit",
      "WidgetKit",
      "Gemini AI",
      "LaTeX",
      "UserNotifications",
      "Git",
    ],
    id: "11",
    achievements: [
      "Implemented a full Spaced Repetition System (SRS) algorithm with four review queues — Critical, Soon, Stable, and Mastered — each backed by separate CoreData entities.",
      "Engineered five card types: FlashCard, True/False, Multiple Choice, Note, and Fill-in-the-Blank, each with a distinct backside interaction model.",
      "Integrated Gemini AI (GeminiService) for AI-powered card generation from text or images, including camera capture and image card support.",
      "Added LaTeX rendering, Markdown import/export, WidgetKit home-screen widget, achievement system, 7 color themes, and local push notifications.",
    ],
    gradient: "from-violet-600 to-purple-700",
    images: [
      "/images/spaced/IMG_2489.png",
      "/images/spaced/IMG_2490.png",
      "/images/spaced/IMG_2491.png",
      "/images/spaced/IMG_2492.png",
      "/images/spaced/IMG_2493.png",
      "/images/spaced/IMG_2494.png",
      "/images/spaced/IMG_2495.png",
      "/images/spaced/IMG_2496.png",
      "/images/spaced/IMG_2497.png",
      "/images/spaced/IMG_2498.png",
      "/images/spaced/IMG_2499.png",
      "/images/spaced/IMG_2500.png",
      "/images/spaced/IMG_2501.png",
    ],
  },
  {
    title: "WarZone",
    company: "Cuneyt Yildirim",
    technologies: ["C++"],
    id: "13",
    achievements: [
      "Engineered a turn-based strategy simulation engine in pure C++, implementing game-state management, player turns, and win-condition evaluation without external frameworks.",
      "Designed a map and territory system allowing players to conquer, reinforce, and defend regions through strategic troop deployment and attack mechanics.",
      "Implemented AI opponent logic with rule-based decision trees for automated attack, defend, and fortify actions during computer-controlled turns.",
      "Architected the game using object-oriented design with clean separation between game engine, player entities, territory models, and UI rendering layers.",
    ],
    gradient: "from-red-700 to-slate-800",
    link: "https://github.com/June8Yildirim/WarZone",
  },
  {
    title: "Chores Auction iOS",
    company: "Cuneyt Yildirim",
    technologies: ["SwiftUI", "Swift", "CoreData", "CloudKit", "Git"],
    id: "12",
    achievements: [
      "Built a household chore management app using CloudKit public database for real-time team sharing without a custom backend.",
      "Implemented team share codes allowing households to join a shared workspace where chores are visible and assignable across all members.",
      "Designed CoreData models with teamId and assignedPerson fields enabling per-team chore ownership and local-first offline access.",
      "Shipped full privacy policy compliance with data-minimization patterns using CloudKit's public record zones.",
    ],
    gradient: "from-orange-600 to-amber-600",
    images: [
      "/images/chores/IMG_2509.png",
      "/images/chores/IMG_2510.png",
      "/images/chores/IMG_2511.png",
      "/images/chores/IMG_2512.png",
      "/images/chores/IMG_2513.png",
      "/images/chores/IMG_2514.png",
    ],
  },
  {
    title: "Ordering Pizza Management",
    company: "Cuneyt Yildirim",
    technologies: [
      "React Native",
      "Expo",
      "TypeScript",
      "Expo Router",
      "React Context API",
    ],
    id: "14",
    achievements: [
      "Built a dual-mode pizza ordering system — a fully customizable builder with topping selection and an animated arch-scroll picker for pre-configured pizzas — both feeding a shared context-driven basket with real-time price calculation.",
      "Engineered a dynamic size-selection system (S/M/L/XL) with size-responsive visual scaling of pizza and plate images, giving users immediate tactile feedback as they switch between sizes.",
      "Implemented a full-featured Admin dashboard with inline CRUD for toppings (meat, vegetable, seafood, and cheese categories with enable/disable toggles), sizes (diameter, slices, servings, base price), pizza types, and pre-built menu items — with a live stats header tracking totals across all entities.",
      "Architected a React Context state layer managing the basket, order history, and user profile across the app, persisting completed orders with status badges, itemized receipts, and formatted order IDs.",
    ],
    gradient: "from-sky-300 to-emerald-300",
    images: [
      "/images/pizza/IMG_2610.png",
      "/images/pizza/IMG_2611.png",
      "/images/pizza/IMG_2612.png",
      "/images/pizza/IMG_2613.png",
      "/images/pizza/IMG_2614.png",
      "/images/pizza/IMG_2615.png",
      "/images/pizza/IMG_2616.png",
      "/images/pizza/IMG_2617.png",
      "/images/pizza/IMG_2618.png",
      "/images/pizza/IMG_2619.png",
      "/images/pizza/IMG_2620.png",
      "/images/pizza/IMG_2621.png",
      "/images/pizza/IMG_2622.png",
      "/images/pizza/IMG_2623.png",
      "/images/pizza/IMG_2624.png",
      "/images/pizza/IMG_2625.png",
      "/images/pizza/IMG_2626.png",
      "/images/pizza/IMG_2627.png",
    ],
  },
  {
    id: "15",
    title: "PRO-BALL ANALYTICA",
    company: "Cuneyt Yildirim",
    technologies: [
      "TypeScript",
      "React 19",
      "TanStack Start",
      "TanStack Router",
      "TanStack Query",
      "MongoDB",
      "Mongoose",
      "TailwindCSS",
      "Vite",
    ],
    achievements: [
      "Architected a full-stack NBA scouting platform with four analytical modules — War Room, Player Profile, Statistical Deep Dive, and Head-to-Head Comparison — all powered by live MongoDB queries via TanStack Start server functions.",
      "Built a League Efficiency Quadrant using pure SVG, dynamically plotting all 30 NBA teams by offensive and defensive rating with auto-scaled axes and four labeled performance zones.",
      "Engineered a player Skill Fingerprint radar chart and career scoring sparkline rendered entirely in SVG, with percentile color-coding and interactive season/team/player dropdowns backed by React Query.",
      "Implemented a Head-to-Head Comparison engine comparing two players across 8 advanced metrics (PER, TS%, BPM, VORP, USG%) with mirrored bar charts, edge summaries, and an auto-generated scouting synopsis.",
    ],
    gradient: "from-orange-600 to-red-600",
    images: [],
  },
  {
    id: "crm-customer-manager",
    title: "Multi-Tenant Warehouse CRM",
    company: "Customer Manager",
    technologies: [
      "Next.js 16 (App Router)",
      "React 19",
      "TypeScript",
      "Prisma 7",
      "PostgreSQL (NeonDB)",
      "NextAuth (2FA / TOTP)",
      "TanStack Query & Table",
      "Zod",
      "Zustand",
      "Tailwind CSS",
      "Pusher (realtime)",
      "Twilio / Nodemailer",
      "Recharts",
      "Vitest / Playwright / Cypress",
    ],
    achievements: [
      "Built a full multi-tenant CRM with per-warehouse data isolation — every customer, invoice, inventory, supplier and fleet query is scoped by warehouseId, with a null-safe global fallback for backward compatibility",
      "Implemented two-factor authentication (TOTP) with QR provisioning on top of NextAuth credential login",
      "Delivered end-to-end business modules: customers, suppliers, inventory, invoicing, and fleet management (trucks & drivers) with tabbed CRUD forms",
      "Designed configurable app settings with per-warehouse overrides and global defaults, plus user-editable constants/options",
      "Layered a controller/API architecture (backend controllers + App Router route handlers) with a dedicated tenant-scoping utility",
      "Covered the codebase with a three-tier test suite (Vitest unit/API, Playwright e2e, Cypress) including tenant-scope isolation tests",
      "Added realtime notifications and multi-channel messaging via Pusher, Twilio SMS, and email",
    ],
    mainImage: "/images/crm/1.png",
    images: [
      "/images/crm/1.png",
      "/images/crm/2.png",
      "/images/crm/3.png",
      "/images/crm/4.png",
      "/images/crm/5.png",
      "/images/crm/6.png",
      "/images/crm/7.png",
      "/images/crm/8.png",
      "/images/crm/9.png",
      "/images/crm/10.png",
      "/images/crm/11.png",
      "/images/crm/12.png",
    ],
    gradient: "from-indigo-500 via-purple-500 to-pink-500",
    link: "https://inventory-management-yildirim.netlify.app/",
  },
  {
    id: "git-learner",
    title: "Interactive Visual Git Playground",
    company: "Personal Project",
    technologies: [
      "React 19",
      "TypeScript",
      "Vite",
      "React Router 7",
      "Oxlint",
      "Netlify",
    ],
    achievements: [
      "Built a Git engine from scratch — a pure, in-memory state machine modeling commits, branches, HEAD, and working/merging states, with an immutable (never-mutate-prev) command dispatcher",
      "Implemented 16 real Git commands including init, add, commit, branch, checkout, merge, rebase, cherry-pick, revert, reset, tag, remote, push, pull, log, and status — plus conflict resolution",
      "Created a live commit graph that draws branches, merges, rebases, and conflicts in real time as learners type real commands into a terminal",
      "Designed a puzzle system that shape-matches a learner's resulting graph against a target signature to validate solutions, with beginner/intermediate difficulty progression",
      "Architected the codebase with clean, typed domain boundaries (engine / hooks / components / lib) so the pure engine is predictable and unit-testable",
    ],
    mainImage: "/src/assets/hero.png",
    images: [
      "/images/gitlearner/1.png",
      "/images/gitlearner/2.png",
      "/images/gitlearner/3.png",
      "/images/gitlearner/4.png",
      "/images/gitlearner/5.png",
      "/images/gitlearner/6.png",
      "/images/gitlearner/7.png",
      "/images/gitlearner/8.png",
      "/images/gitlearner/9.png",
      "/images/gitlearner/10.png",
      "/images/gitlearner/11.png",
      "/images/gitlearner/12.png",
    ],
    gradient: "from-orange-800 via-orange-500 to-emerald-600",
    link: "https://gitpractising.netlify.app/",
  },
  {
    id: "web-dev-toolkit",
    title: "Web Dev Toolkit",
    company: "Personal Project",
    technologies: [
      "React 19",
      "React Router 8",
      "TypeScript",
      "Tailwind CSS v4",
      "Vite 8",
      "react-markdown",
      "@cuneytyildirim/ui",
    ],
    achievements: [
      "Built a single categorized, searchable documentation hub for 17 of the web ecosystem's most-used packages (Zod, TanStack Query, Prisma, Drizzle, tRPC, GraphQL, Tailwind CSS, shadcn/ui, NextAuth, Playwright, Git and more)",
      "Designed a registry-driven architecture where adding a new tool is a single declarative entry that auto-wires the sidebar, landing grid, and dynamic route",
      "Delivered a persistent-sidebar layout with category grouping (validation, data fetching, database, styling, auth, testing, tooling) and rich, interactive per-tool doc pages",
      "Separated content from presentation by authoring docs as Markdown loaded at build time and rendered through a shared react-markdown + remark-gfm pipeline",
      "Powered every page with my own published component library, @cuneytyildirim/ui, for coherent theming, badges, tabs, and typography",
    ],
    gradient: "from-blue-500 to-indigo-600",
    link: "https://github.com/cuneytyildirim/webdevtoolkits",
  },
  {
    id: "crm-customer-manager",
    title: "CRM Customer Manager",
    company: "Acme Logistics",
    technologies: [
      "Next.js (App Router)",
      "TypeScript",
      "Prisma",
      "NeonDB (Postgres)",
      "Tailwind CSS",
    ],
    achievements: [
      "Built a multi-tenant warehouse isolation layer scoping every controller and API route by warehouseId",
      "Implemented 2FA authentication for all admin users",
      "Designed an updatable settings system with tabbed forms for drivers, trucks, and options",
      "Cut invoice generation time by 40% with server-side rendering and caching",
    ],
    mainImage: "/projects/crm/dashboard.png",
    images: [
      "/projects/crm/invoices.png",
      "/projects/crm/fleet.png",
      "/projects/crm/settings.png",
    ],
    gradient: "from-indigo-500 via-purple-500 to-pink-500",
    link: "https://crm.example.com",
  },
];
